from .user_repo import UserRepository
from .profile_repo import ProfileRepository
from .education_repo import EducationRepository
from .certification_repo import CertificationRepository
from .achievement_repo import AchievementRepository
from .document_repo import DocumentRepository
from .experiment_repo import ExperienceRepository
from .publication_repo import PublicationRepository
from .reference_repo import ReferenceRepository
